// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdf1PqZYXbqFdBIXqtJP8-ZKkueGG7hqo',
    appId: '1:204976102032:web:45eefe28b08ed8cc771615',
    messagingSenderId: '204976102032',
    projectId: 'travelexplor-1a5fe',
    authDomain: 'travelexplor-1a5fe.firebaseapp.com',
    storageBucket: 'travelexplor-1a5fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIOSf_3ANUUFGqm6nSSzTrJW_4jTdWDiQ',
    appId: '1:204976102032:android:4f43f57c7dcdc26a771615',
    messagingSenderId: '204976102032',
    projectId: 'travelexplor-1a5fe',
    storageBucket: 'travelexplor-1a5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSTCeEBqTPsy1b3heIOUJjugs2qGXjG3g',
    appId: '1:204976102032:ios:b928e1dfcf33786d771615',
    messagingSenderId: '204976102032',
    projectId: 'travelexplor-1a5fe',
    storageBucket: 'travelexplor-1a5fe.firebasestorage.app',
    iosBundleId: 'com.example.travelExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSTCeEBqTPsy1b3heIOUJjugs2qGXjG3g',
    appId: '1:204976102032:ios:b928e1dfcf33786d771615',
    messagingSenderId: '204976102032',
    projectId: 'travelexplor-1a5fe',
    storageBucket: 'travelexplor-1a5fe.firebasestorage.app',
    iosBundleId: 'com.example.travelExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdf1PqZYXbqFdBIXqtJP8-ZKkueGG7hqo',
    appId: '1:204976102032:web:f63ab37c1b873582771615',
    messagingSenderId: '204976102032',
    projectId: 'travelexplor-1a5fe',
    authDomain: 'travelexplor-1a5fe.firebaseapp.com',
    storageBucket: 'travelexplor-1a5fe.firebasestorage.app',
  );
}
